// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace NotaEstudiantes.Models
{
    public partial class Estudiante
    {
        public Estudiante()
        {
            Instructor = new HashSet<Instructor>();
            Nota = new HashSet<Nota>();
        }

        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string Jornada { get; set; }
        public string Correo { get; set; }
        public string Contraseña { get; set; }
        public string ImagenUrl { get; set; }
        [NotMapped]
        public IFormFile ImagenFile { get; set; }
        public int? IdEstado { get; set; }
        public int? IdAsistencia { get; set; }
        public int? IdJornadaI { get; set; }

        public virtual Asistencia IdAsistenciaNavigation { get; set; }
        public virtual Estado IdEstadoNavigation { get; set; }
        public virtual Jornada IdJornadaINavigation { get; set; }
        public virtual ICollection<Instructor> Instructor { get; set; }
        public virtual ICollection<Nota> Nota { get; set; }
    }
}