// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NotaEstudiantes.Models
{
    public partial class Instructor
    {
        public int Id { get; set; }
        public string NombreInstructor { get; set; }
        public string Direccion { get; set; }
        public string Matreria { get; set; }
        public string Telefono { get; set; }
        public int? IdJornada { get; set; }
        public int? IdEstudianteI { get; set; }
        public int? IdMateriaI { get; set; }

        public virtual Estudiante IdEstudianteINavigation { get; set; }
        public virtual Jornada IdJornadaNavigation { get; set; }
        public virtual Materia IdMateriaINavigation { get; set; }
    }
}