// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NotaEstudiantes.Models
{
    public partial class Jornada
    {
        public Jornada()
        {
            Estudiante = new HashSet<Estudiante>();
            Instructor = new HashSet<Instructor>();
        }

        public int Id { get; set; }
        public string Jornada1 { get; set; }

        public virtual ICollection<Estudiante> Estudiante { get; set; }
        public virtual ICollection<Instructor> Instructor { get; set; }
    }
}