// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace NotaEstudiantes.Models
{
    public partial class Materia
    {
        public Materia()
        {
            Instructor = new HashSet<Instructor>();
            Nota = new HashSet<Nota>();
        }

        public int Id { get; set; }
        public string NombreMateria { get; set; }

        public virtual ICollection<Instructor> Instructor { get; set; }
        public virtual ICollection<Nota> Nota { get; set; }
    }
}